import binascii
import os
import re
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple, Dict

from . import __version__

CRC_REGEX = r"[^\\\[\\(]*?([\\\[\\(])([0-9a-f]{8})([\\\]\\)])[^/]*$"


def crc32_from_file(filepath: str) -> str:
    """Calculate CRC32 checksum for a file."""
    with open(filepath, "rb") as file:
        checksum = binascii.crc32(file.read()) & 0xFFFFFFFF
        return f"{checksum:08X}"


def extract_crc_from_filename(filepath: str) -> Optional[str]:
    """Extract CRC32 from a filename."""
    match = re.search(CRC_REGEX, filepath, re.I)
    return match.group(2).upper() if match else None


def verify_in_filename(filepath: str) -> Tuple[Optional[str], str]:
    """Verify CRC32 in filename against calculated CRC32."""
    filename_crc = extract_crc_from_filename(filepath)
    calculated_crc = crc32_from_file(filepath)
    return filename_crc, calculated_crc


def append_to_filename(filepath: str) -> None:
    """Append CRC32 to filename if not already present."""
    if extract_crc_from_filename(filepath):
        return

    path = Path(filepath)
    crc = crc32_from_file(filepath)
    new_path = path.with_name(f"{path.stem} [{crc}]{path.suffix}")
    os.rename(filepath, new_path)


def parse_sfv_line(line: str) -> Optional[Tuple[str, str]]:
    """Parse a line from an SFV file."""
    line = line.strip()
    if not line or line.startswith(";"):
        return None

    match = re.match(r'(.*?)\s+([0-9A-Fa-f]{8})$', line)
    if not match:
        return None

    return match.group(1), match.group(2).upper()


def verify_sfv_file(sfv_filepath: str) -> List[Dict]:
    """Verify files listed in an SFV file."""
    results = []
    sfv_dir = Path(sfv_filepath).parent

    with open(sfv_filepath, "r", encoding="utf-8") as f:
        for line in f:
            parsed = parse_sfv_line(line)
            if not parsed:
                continue

            filepath_str, expected_crc = parsed
            filepath = sfv_dir / filepath_str
            result = {
                "file": filepath_str,
                "expected_crc": expected_crc,
                "actual_crc": None,
                "ok": False,
            }

            try:
                actual_crc = crc32_from_file(str(filepath))
                result["actual_crc"] = actual_crc
                if actual_crc == expected_crc:
                    result["ok"] = True
            except FileNotFoundError:
                pass  # Keep status as not found

            results.append(result)

    return results


def create_sfv_file(sfv_filepath: str, filepaths: List[str]) -> None:
    """Create an SFV file for the given files."""
    with open(sfv_filepath, "w", encoding="utf-8") as f:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        f.write(f"; Generated by ZenCRC v{__version__} on {timestamp}\n")
        for filepath in filepaths:
            try:
                crc = crc32_from_file(filepath)
                f.write(f"{Path(filepath).name} {crc}\n")
            except (FileNotFoundError, IsADirectoryError):
                continue